/**
 * SmartCatfish — Normalization Parameters for AI Inference
 * Auto-generated by train_do_model.py
 * These MUST match the MinMaxScaler used during training!
 */

#ifndef DO_NORM_PARAMS_H
#define DO_NORM_PARAMS_H

const float TEMP_MIN = 20.0001f;
const float TEMP_MAX = 37.9995f;
const float WL_MIN   = 5.0008f;
const float WL_MAX   = 99.9992f;
const float LDR_MIN  = 0.0016f;
const float LDR_MAX  = 99.9989f;
const float DO_MIN   = 0.0000f;
const float DO_MAX   = 8.9031f;

#endif // DO_NORM_PARAMS_H
